on:
  schedule:
    - cron: '30 * * * *'
  workflow_dispatch:

permissions: write-all

defaults:
  run:
    shell: bash
    working-directory: ./

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Download antizapret pac file
      run: |
        mkdir -p data
        wget -O data/proxy.pac -- 'https://antizapret.prostovpn.org/proxy.pac'
    - name: Commit files # transfer the new html files back into the repository
      run: |
        git config --local user.name "ghactions"
        git add ./data
        git commit -m "Updating the repository"
    - name: Push changes # push the output folder to your repo
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        force: true
 
