on:
  schedule:
    - cron: '30 * * * *'
  workflow_dispatch:

permissions: write-all

defaults:
  run:
    shell: bash
    working-directory: ./

jobs:
  build:
    env:
      SUCC: 0
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Download antizapret pac file
      run: |
        mkdir -p conf
        wget -O proxy.pac -- 'https://antizapret.prostovpn.org/proxy.pac'
        awk -f ./scripts/antizapret2clash.awk ./proxy.pac
        rm ./proxy.pac
    - name: Commit files # transfer the new html files back into the repository
      run: |
        git config --local user.name "ghactions"
        git add ./conf
        git commit -m "Updating the repository" || SUCC=1
    - name: Push changes # push the output folder to your repo
      if: ${{ SUCC=0 }}
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        force: true
 
