on:
  schedule:
    - cron: '30 * * * *'
  workflow_dispatch:
defaults:
  run:
    shell: bash
    working-directory: ./
jobs:
  configurator:
    runs-on: ubuntu-latest
    steps:
    - name: Download antizapret pac file
      run: |
        pwd
        ls -ral
        #wget -O data/proxy.pac -- 'https://antizapret.prostovpn.org/proxy.pac'
